[tool.poetry]
name = "least-watched"
version = "0.1.0"
description = ""
authors = ["seansusmilch <seantsusmilch@gmail.com>"]
readme = "README.md"
packages = [
    { include = "main", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
